### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Badozoki** [ading2210/shimboot#96] opened 2024-09-26 21:48 UTC
I have a problem running shimboot im on a acer chromebook on jaccuzi and when i press power esc refresh then ctrl+d for the devlopper mode then turn off the os verification and finally press power esc refresh i plug in my usb key with the jacuzzi 1.2.1 version of shimboot i have a blakc screen with no mouse just nothing

**Comment by ading2210** [comment] 2024-09-28 00:01
This is a duplicate of #78.

**Closed by ading2210** 2024-09-28 00:01 UTC
Labels: duplicate
