### ISSUE TITLE
won't extend storage

### ISSUE THREAD

**Issue by Clone-trooper-9904** [ading2210/shimboot#143] opened 2024-10-28 22:10 UTC
I was trying to extend my storage on the linix software and it ended up in an fail 

![Screenshot_2024-10-28_22-09-15](https://github.com/user-attachments/assets/a9db4d25-6418-435e-b3d7-95fe7f513f24)

**Comment by ading2210** [comment] 2024-10-29 02:54
This is a duplicate of #60 which is already fixed in a different branch.

**Closed by ading2210** 2024-10-29 02:54 UTC
Labels: duplicate

**Comment by Clone-trooper-9904** [comment] 2024-10-29 11:47
than how do i do it
