### ISSUE TITLE
ChromeOS won't boot in root-A or B on octopus dell 3100

### ISSUE THREAD

**Issue by coolestDude19** [ading2210/shimboot#126] opened 2024-10-17 08:39 UTC
**To Reproduce**
1. Go to 'the shimboot os selector'
2. Click on 'ChromeOS_ROOT-A or ROOT-B'

**Expected behavior**
I would expect chromeOS to boot after some time

**Screenshots / Photos**
I have waited 5 minutes and no change
![IMG_20241017_04343800~2](https://github.com/user-attachments/assets/62b77b06-df66-4d12-b657-e575f813ebf8)

**Target Chrome OS Device (please complete the following information):**
 - Board Name octopus
 - Device Name fleex
 - Shimboot version v1.2.1

**Comment by NikhilKonduru8** [comment] 2024-10-17 14:37
You have to boot from your USB drive or whatever you used to flash your linux onto

**Comment by coolestDude19** [comment] 2024-10-17 20:38
I had booted it and extended the rootfs then I booted chromeos

**Comment by ifee11ikeiediagcmdrn** [comment] 2024-10-17 20:50
yeah same thing here, i wasted over 15 minutes, i also tried Booting from my USB, and it didnt work.

**Comment by ifee11ikeiediagcmdrn** [comment] 2024-10-17 20:51
dell is also ass, so, why wouldn't everything go horribly?

**Comment by Fighterhen63** [comment] 2024-10-18 21:36
@coolestDude19 https://github.com/ading2210/shimboot/issues/37#issuecomment-2222246910

**Comment by ading2210** [comment] 2024-10-18 23:08
This is a duplicate of #20.

**Closed by ading2210** 2024-10-18 23:08 UTC
Labels: duplicate
