### ISSUE TITLE
Google play store not working on 128 can't down grade

### ISSUE THREAD

**Issue by Dominicis1** [ading2210/shimboot#90] opened 2024-09-23 03:50 UTC
When I boot into the chrome os and try to use play store on version 128 it doesn't work but when I do it on another computer on version 116 its able to open and work but I can't down grade so idk if its supposed to be like that but ya would like a little help

**Comment by Tulip-0333** [comment] 2024-09-23 23:28
Have you tried resetting the partition? Are you signed in with a lone (non-child, non-managed) Google account?

**Comment by ading2210** [comment] 2024-09-24 08:46
This is a duplicate of #51.

**Closed by ading2210** 2024-09-24 08:46 UTC
Labels: duplicate

**Comment by Dominicis1** [comment] 2024-09-25 11:31
figured out how to downgrade and make it work

**Comment by Noob0dooN** [comment] 2024-11-28 22:16
@Dominicis1 But how did you do it?
