### ISSUE TITLE
Wifi not working on grunt

### ISSUE THREAD

**Issue by Go0gl** [ading2210/shimboot#75] opened 2024-09-18 15:03 UTC
**Describe the bug**

**To Reproduce**
1. Go to 'wifi'
2. Click on 'connect thing'
4. See that there isn't anything to connect to

**Expected behavior**
To be able to connect to wireless wifi

**Screenshots / Photos**
sorry don't have any, able to take some if needed

**Target Chrome OS Device (please complete the following information):**
 - Board Name (grunt)
 - Device Name (barla)
 - Shimboot version (most recent

**Comment by Go0gl** [comment] 2024-09-18 15:05
also,  [https://github.com/ading2210/shimboot/issues/69](url) didn't work for me

**Comment by Raf128** [comment] 2024-09-18 16:19
what is the output of lspci

**Comment by Raf128** [comment] 2024-09-18 23:12
i guessed that

**Comment by ading2210** [comment] 2024-09-19 19:56
This is a duplicate of #69. Also, you do not need to sign kernel modules for them to work.

**Closed by ading2210** 2024-09-19 19:56 UTC
Labels: duplicate
