### ISSUE TITLE
Unable to update or install most apps

### ISSUE THREAD

**Issue by ImNotMrFoxGaming** [ading2210/shimboot#200] opened 2024-12-12 17:54 UTC
The bug is when using command line to install just about anything, it always gives an error, the only time it worked was with the minecraft launcher and that was it.

Doing any form of sudo apt install will cause this with most programs, usually saying things like amd64 or i386 are missing or other software that cannot be installed.

An app should be able to install when the .deb is in the main folder, not anything like downloads.

 - Board Name (e.g. octopus
 - Device Name (garg or garg 360)
 - Shimboot version ( v1.0.1) 

 - OS: [Debian 12]
 - Neofetch out [not installed]
 - Shimboot version ( v1.0.1)

**Comment by Fighterhen63** [comment] 2024-12-12 20:40
Was this happening when you first flashed shimboot?

**Comment by ading2210** [comment] 2024-12-12 20:53
Please run `sudo apt update` and `sudo apt upgrade` before trying to install any new packages.

**Comment by ImNotMrFoxGaming** [comment] 2024-12-13 16:19
I tried sudo apt update didn’t do anything

**Comment by ImNotMrFoxGaming** [comment] 2024-12-13 16:23
After checking its v1.2.1, here is a picture of sudo apt upgrade 
![image](https://github.com/user-attachments/assets/e4a69a39-88d2-4704-9210-dd8be434c198)

**Comment by Fighterhen63** [comment] 2024-12-13 16:25
Do sudo su then type in ur password then try apt again

**Comment by ImNotMrFoxGaming** [comment] 2024-12-13 16:46
It helped me get further, but it is stuck on [waiting for headers 0%] as
well as repeating the error following.
Ign:8 https://shimboot.pages.dev/debian bookworm all Contents (deb)
Err:9 https://shimboot.pages.dev/debian bookworm amd64 Contents (deb)
  404  Not Found [IP: REDACTED]

**Comment by ImNotMrFoxGaming** [comment] 2024-12-13 16:50
> Was this happening when you first flashed shimboot?

yes it was.

**Comment by ImNotMrFoxGaming** [comment] 2024-12-13 16:50
> Please run `sudo apt update` and `sudo apt upgrade` before trying to install any new packages.

tried that before and it did not do anything

**Comment by ImNotMrFoxGaming** [comment] 2024-12-13 16:51
> The bug is when using command line to install just about anything, it always gives an error, the only time it worked was with the minecraft launcher and that was it.
> 
> Doing any form of sudo apt install will cause this with most programs, usually saying things like amd64 or i386 are missing or other software that cannot be installed.
> 
> An app should be able to install when the .deb is in the main folder, not anything like downloads.
> 
>     * Board Name (e.g. octopus
> 
>     * Device Name (garg or garg 360)
> 
>     * Shimboot version ( v1.2.1)
> 
>     * OS: [Debian 12]
> 
>     * Neofetch out [not installed]
> 
>     * Shimboot version ( v1.2.1)

**Comment by ImNotMrFoxGaming** [comment] 2024-12-13 16:55
here are some more errors i got.
Ign:3 https://shimboot.pages.dev/debian bookworm/main all Packages
Ign:5 https://shimboot.pages.dev/debian bookworm/main Translation-en
Ign:6 https://shimboot.pages.dev/debian bookworm/main amd64 Contents (deb)
Ign:7 https://shimboot.pages.dev/debian bookworm/main all Contents (deb)
Ign:8 https://shimboot.pages.dev/debian bookworm all Contents (deb)
Ign:9 https://shimboot.pages.dev/debian bookworm amd64 Contents (deb)
Ign:10 http://deb.debian.org/debian bookworm InRelease                                                                               
Ign:10 http://deb.debian.org/debian bookworm InRelease
Ign:10 http://deb.debian.org/debian bookworm InRelease

**Comment by TheTruePerson** [comment] 2024-12-14 22:05
those aren't errors. you need to always use sudo before apt.

try this:
sudo apt-get update
sudo apt install (name of the thing)


also try doing
sudo apt-get update
sudo apt remove google-chrome-stable
sudo apt install google-chrome-stable --install-recommends --install-suggests

**Comment by TheTruePerson** [comment] 2024-12-14 22:06
and for steam launcher, run sudo apt-get update and then right after run sudo apt install steam-launcher

**Comment by ImNotMrFoxGaming** [comment] 2024-12-16 17:17
> and for steam launcher, run sudo apt-get update and then right after run sudo apt install steam-launcher

both just get stuck on waiting for headers after a bunch of stuff shows up starting with ign and a number of 1-9

**Comment by TheTruePerson** [comment] 2024-12-16 23:10
be patient bruv its loading

**Comment by ImNotMrFoxGaming** [comment] 2024-12-17 05:15
I left it on for 5 hours, did not change at all

**Comment by goober3853** [comment] 2024-12-18 01:42
I don't think steam even works through normal methods

It works with wine, though.

**Comment by TheTruePerson** [comment] 2024-12-18 11:35
Yes steam does work natively, perfectly fine. You need to install it from the package downloaded form the website, and you need to launch it with STEAM_DEBUG=1 steam --no-cef-sandbox -no-cef-sandbox

if you get an issue about steamwebhelper crashing select restart steamwebhelper with gpu acceleration off
if it just stops then start it again
if you get an error about libc.so that means that you interupted it on the first launch or during an update, you should be able to just ignore it though

**Comment by ading2210** [comment] 2024-12-18 20:39
@ImNotMrFoxGaming Can you make sure https://shimboot.pages.dev/debian/ is not blocked for you?

**Comment by ImNotMrFoxGaming** [comment] 2024-12-22 23:58
Turns out, my isp said fuck you and all I had to do was use my hotspot, I have steam installed, it’s just that user namespaces aren’t working

**Comment by ading2210** [comment] 2024-12-23 05:17
https://github.com/ading2210/shimboot?tab=readme-ov-file#steam-doesnt-work

Closing as this is not a bug with shimboot.

**Closed by ading2210** 2024-12-23 05:17 UTC
Labels: bug
