### ISSUE TITLE
Weird visual bug on Nissa board

### ISSUE THREAD

**Issue by TheTruePerson** [ading2210/shimboot#176] opened 2024-11-20 21:29 UTC
**Describe the bug**
See the Google Drive video to see it.  Edit: for clarification, the bug happens at the end. I tried leaving it for a few hours but it didn't fix itself. I just included the rest of it in case it helped.

**To Reproduce**
Not really sure how to reproduce - shimboot was working fine until now. When i do the normal boot sequence (enable devmode, plug in usb (i have a good 3.0 one, its pretty fast), 3, enter, and then login with user and user)

**Expected behavior**
It should just boot into Xfce desktop as normal.

**Screenshots / Photos**
https://drive.google.com/file/d/1r0AHBckRs2VgCylIB1eDsEhcvA1xDK00/view?usp=sharing 

**Target Chrome OS Device (please complete the following information):**
 - Board Name nissa
 - Device Name hulx 
 - Shimboot version  v1.2.1

**Additional context**
i did do sudo apt remove python3 bc i was tryna fix some problems, and apt decided to delete steam and some xfce packages and some libreoffice packages and a bunch of other ones. after that rebooting i got this issue

I'm assuming this is a shimboot bug because I couldn't find any other documentation , but if it isn't I'd really love some suggestions to fix it. I lost a bunch of projects and Minecraft worlds - (Although i could probably retrieve by plugging it into.a different computer)

**Comment by ading2210** [comment] 2024-11-20 21:36
You broke your system packages. Plug the USB into a different linux system, chroot into the rootfs, and reinstall `task-xfce-desktop`. As long as you `apt update` and `apt upgrade` before installing or removing stuff, this should never happen. 

I'm going to close this because I'm inclined to believe that it's user error, and you didn't provide any way to reproduce it anyways.

**Closed by ading2210** 2024-11-20 21:36 UTC
Labels: bug

**Comment by TheTruePerson** [comment] 2024-11-20 23:25
> You broke your system packages. Plug the USB into a different linux system, chroot into the rootfs, and reinstall `task-xfce-desktop`. As long as you `apt update` and `apt upgrade` before installing or removing stuff, this should never happen.
> 
> I'm going to close this because I'm inclined to believe that it's user error, and you didn't provide any way to reproduce it anyways.

alright, thanks!
